version: '3'

services:
  app:
    entrypoint: sh -c "npm install && npm run start:dev"
    build: .
    volumes:
      - '.:/home/node/app'
    ports:
      - '3000:3000' # expose ports - HOST:CONTAINER

